Repository laminas/laminas-ci-matrix-action, pull requests merged in 2022-08, with the labels that each got.

#117 Update required node version to match the one installed
  entrypoint.sh
  package-lock.json
  package.json
  src/config/app.ts
  src/config/input.ts
  tsconfig.json
Labels: Enhancement

#31 Use `XmlLint` against tool configurations (PHPUnit, PHPCS, Psalm)
  package.json
  src/action/github.ts
  src/config/app.ts
  src/config/input.ts
  src/config/output.ts
  src/tools.ts
  tests/code-check-codeception-dist/matrix.json
  tests/code-check-codeception-nodist/matrix.json
  tests/code-check-composer-require-checker/matrix.json
  tests/code-check-deprecated-exclusion-via-config/matrix.json
  tests/code-check-exclusion-via-config/matrix.json
  tests/code-check-infection-dist/matrix.json
  tests/code-check-infection-nodist/matrix.json
  tests/code-check-infection-roave-static-analysis-plugin-dist/matrix.json
  tests/code-check-infection-roave-static-analysis-plugin-nodist/matrix.json
  tests/code-check-locked-dependencies/matrix.json
  tests/code-check-phpbench/matrix.json
  tests/code-check-phpcs-dist/matrix.json
  tests/code-check-phpcs-nodist/matrix.json
  tests/code-check-phpunit-dist-due-to-laminas-ci-json-change/matrix.json
  tests/code-check-phpunit-dist/matrix.json
  tests/code-check-phpunit-nodist/matrix.json
  tests/code-check-psalm-dist/matrix.json
  tests/code-check-psalm-nodist/matrix.json
  tests/code-checks-without-linting-due-to-diff/matrix.json
  tests/doc-linting-doc-book/matrix.json
  tests/doc-linting-docs-book/matrix.json
  tests/doc-linting-mkdocs/matrix.json
  tests/doc-linting-without-code-checks-due-diff/matrix.json
  tests/no-checks-due-to-diff/matrix.json
  tests/no-checks/matrix.json
Labels: Enhancement

#122 Revert "Use `XmlLint` against tool configurations (PHPUnit, PHPCS, Psalm)"
  package.json
  src/action/github.ts
  src/config/app.ts
  src/config/input.ts
  src/config/output.ts
  src/tools.ts
  tests/code-check-codeception-dist/matrix.json
  tests/code-check-codeception-nodist/matrix.json
  tests/code-check-composer-require-checker/matrix.json
  tests/code-check-deprecated-exclusion-via-config/matrix.json
  tests/code-check-exclusion-via-config/matrix.json
  tests/code-check-infection-dist/matrix.json
  tests/code-check-infection-nodist/matrix.json
  tests/code-check-infection-roave-static-analysis-plugin-dist/matrix.json
  tests/code-check-infection-roave-static-analysis-plugin-nodist/matrix.json
  tests/code-check-locked-dependencies/matrix.json
  tests/code-check-phpbench/matrix.json
  tests/code-check-phpcs-dist/matrix.json
  tests/code-check-phpcs-nodist/matrix.json
  tests/code-check-phpunit-dist-due-to-laminas-ci-json-change/matrix.json
  tests/code-check-phpunit-dist/matrix.json
  tests/code-check-phpunit-nodist/matrix.json
  tests/code-check-psalm-dist/matrix.json
  tests/code-check-psalm-nodist/matrix.json
  tests/code-checks-without-linting-due-to-diff/matrix.json
  tests/doc-linting-doc-book/matrix.json
  tests/doc-linting-docs-book/matrix.json
  tests/doc-linting-mkdocs/matrix.json
  tests/doc-linting-without-code-checks-due-diff/matrix.json
  tests/no-checks-due-to-diff/matrix.json
  tests/no-checks/matrix.json
Labels: Bug

#124 Re-release `xmllint` now usage of `before_script` is fixed
  package-lock.json
  package.json
  src/action/github.ts
  src/config/app.ts
  src/config/input.ts
  src/config/output.ts
  src/tools.ts
  tests/code-check-codeception-dist/matrix.json
  tests/code-check-codeception-nodist/matrix.json
  tests/code-check-composer-require-checker/matrix.json
  tests/code-check-deprecated-exclusion-via-config/matrix.json
  tests/code-check-exclusion-via-config/matrix.json
  tests/code-check-infection-dist/matrix.json
  tests/code-check-infection-nodist/matrix.json
  tests/code-check-infection-roave-static-analysis-plugin-dist/matrix.json
  tests/code-check-infection-roave-static-analysis-plugin-nodist/matrix.json
  tests/code-check-locked-dependencies/matrix.json
  tests/code-check-phpbench/matrix.json
  tests/code-check-phpcs-dist/matrix.json
  tests/code-check-phpcs-nodist/matrix.json
  tests/code-check-phpunit-dist-due-to-laminas-ci-json-change/matrix.json
  tests/code-check-phpunit-dist/matrix.json
  tests/code-check-phpunit-nodist/matrix.json
  tests/code-check-psalm-dist/matrix.json
  tests/code-check-psalm-nodist/matrix.json
  tests/code-checks-without-linting-due-to-diff/matrix.json
  tests/doc-linting-doc-book/matrix.json
  tests/doc-linting-docs-book/matrix.json
  tests/doc-linting-mkdocs/matrix.json
  tests/doc-linting-without-code-checks-due-diff/matrix.json
  tests/no-checks-due-to-diff/matrix.json
  tests/no-checks/matrix.json
Labels: Enhancement, Feature Request
