Repository laminas/laminas-ci-matrix-action, pull requests merged in 2022-11, with the labels that each got.

#139 Fix incorrect version extraction when extracting `php` version from `composer.json` constraints
  .github/workflows/continuous-integration.yml
  Dockerfile
  jest.config.ts
  package-lock.json
  package.json
  src/config/app.spec.ts
  src/config/app.ts
  webpack.config.js
  webpack.config.ts
Labels: Bug, Enhancement

#141 Bump node to v19 and enforce strict engine checks
  .github/workflows/continuous-integration.yml
  .npmrc
  package-lock.json
  package.json
Labels: Enhancement

#142 Use correct config key for node-versions
  .github/workflows/continuous-integration.yml
Labels: Bug

#150 Remove deprecated `set-output` action commands
  .github/workflows/build-and-push-containers.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/create-additional-action-tags.yml
Labels: Enhancement
